-- Query 8
-- This query ranks the price of products that are less than $50 and start with an F.
SELECT PRODUCTCATEGORY AS "ProductCategory", PRODUCTDESCR AS "Product Description", TO_CHAR(PRODUCTPRICE, '$99,999.00') AS "Product Price", RANK() OVER(ORDER BY PRODUCTPRICE) AS "Rank" FROM PRODUCT
WHERE PRODUCTCATEGORY LIKE 'F%' AND PRODUCTPRICE < 50
GROUP BY PRODUCTCATEGORY, PRODUCTPRICE, PRODUCTDESCR;


